import 'package:flutter/material.dart';
import 'package:widgetbook/widgetbook.dart';
import 'package:widgetbook_annotation/widgetbook_annotation.dart' as widgetbook;

import 'design_system/foundations/primitives/color_palettes.dart';
import 'design_system/foundations/tokens/app_colors.dart';
import 'design_system/foundations/tokens/app_elevation.dart';
import 'design_system/foundations/tokens/app_radius.dart';
import 'design_system/foundations/tokens/app_spacing.dart';
import 'design_system/foundations/tokens/app_typography.dart';
import 'design_system/themes/app_theme_factory.dart';

/// =============================================================================
/// SINGULAR DESIGN SYSTEM - WIDGETBOOK DOCUMENTATION
/// =============================================================================
/// Documentation and component catalog using Widgetbook 3.0+
/// Provides interactive previews with brand and theme mode switching.
/// =============================================================================

// Generated by build_runner - run `flutter pub run build_runner build`
// import 'widgetbook.directories.g.dart';

void main() {
  runApp(const SingularWidgetbook());
}

/// Main Widgetbook app for Singular Design System
@widgetbook.App()
class SingularWidgetbook extends StatelessWidget {
  const SingularWidgetbook({super.key});

  @override
  Widget build(BuildContext context) {
    return Widgetbook.material(
      // Addons for theme and brand switching
      addons: [
        // Brand selector addon
        BuilderAddon(
          name: 'Brand',
          builder: (context, child) {
            return _BrandAddonWrapper(child: child);
          },
        ),
        // Theme mode addon (Light/Dark)
        ThemeAddon<ThemeData>(
          themes: [
            WidgetbookTheme(
              name: 'Light',
              data: AppThemeFactory.walaPlus.lightTheme,
            ),
            WidgetbookTheme(
              name: 'Dark',
              data: AppThemeFactory.walaPlus.darkTheme,
            ),
          ],
          themeBuilder: (context, theme, child) {
            return Theme(
              data: theme,
              child: child,
            );
          },
        ),
        // Device frame addon
        DeviceFrameAddon(
          devices: [
            Devices.ios.iPhone13,
            Devices.ios.iPadPro11Inches,
            Devices.android.samsungGalaxyS20,
            Devices.android.samsungGalaxyA50,
          ],
          initialDevice: Devices.ios.iPhone13,
        ),
        // Text scale addon
        TextScaleAddon(
          scales: [1.0, 1.25, 1.5, 2.0],
          initialScale: 1.0,
        ),
        // Localization addon
        LocalizationAddon(
          locales: [
            const Locale('en', 'US'),
            const Locale('ar', 'SA'),
          ],
          localizationsDelegates: const [],
          initialLocale: const Locale('en', 'US'),
        ),
      ],

      // Component directories
      directories: [
        // =====================================================================
        // FOUNDATIONS
        // =====================================================================
        WidgetbookCategory(
          name: 'Foundations',
          children: [
            // Colors
            WidgetbookFolder(
              name: 'Colors',
              children: [
                WidgetbookComponent(
                  name: 'Brand Colors',
                  useCases: [
                    WidgetbookUseCase(
                      name: 'WalaPlus Primary',
                      builder: (context) => _ColorSwatchPreview(
                        name: 'WalaPlus Primary',
                        swatch: WalaPlusPrimary.swatch,
                      ),
                    ),
                    WidgetbookUseCase(
                      name: 'WalaPlus Secondary',
                      builder: (context) => _ColorSwatchPreview(
                        name: 'WalaPlus Secondary',
                        swatch: WalaPlusSecondary.swatch,
                      ),
                    ),
                    WidgetbookUseCase(
                      name: 'WalaOne Primary',
                      builder: (context) => _ColorSwatchPreview(
                        name: 'WalaOne Primary',
                        swatch: WalaOnePrimary.swatch,
                      ),
                    ),
                    WidgetbookUseCase(
                      name: 'WalaOne Secondary',
                      builder: (context) => _ColorSwatchPreview(
                        name: 'WalaOne Secondary',
                        swatch: WalaOneSecondary.swatch,
                      ),
                    ),
                    WidgetbookUseCase(
                      name: 'Doam Primary',
                      builder: (context) => _ColorSwatchPreview(
                        name: 'Doam Primary',
                        swatch: DoamPrimary.swatch,
                      ),
                    ),
                    WidgetbookUseCase(
                      name: 'Doam Secondary',
                      builder: (context) => _ColorSwatchPreview(
                        name: 'Doam Secondary',
                        swatch: DoamSecondary.swatch,
                      ),
                    ),
                  ],
                ),
                WidgetbookComponent(
                  name: 'Neutral Palette',
                  useCases: [
                    WidgetbookUseCase(
                      name: 'Slate Scale',
                      builder: (context) => _ColorSwatchPreview(
                        name: 'Neutral (Slate)',
                        swatch: NeutralPalette.swatch,
                      ),
                    ),
                  ],
                ),
                WidgetbookComponent(
                  name: 'Status Colors',
                  useCases: [
                    WidgetbookUseCase(
                      name: 'Success',
                      builder: (context) => _ColorSwatchPreview(
                        name: 'Success',
                        swatch: SuccessPalette.swatch,
                      ),
                    ),
                    WidgetbookUseCase(
                      name: 'Warning',
                      builder: (context) => _ColorSwatchPreview(
                        name: 'Warning',
                        swatch: WarningPalette.swatch,
                      ),
                    ),
                    WidgetbookUseCase(
                      name: 'Error',
                      builder: (context) => _ColorSwatchPreview(
                        name: 'Error',
                        swatch: ErrorPalette.swatch,
                      ),
                    ),
                    WidgetbookUseCase(
                      name: 'Info',
                      builder: (context) => _ColorSwatchPreview(
                        name: 'Info',
                        swatch: InfoPalette.swatch,
                      ),
                    ),
                  ],
                ),
                WidgetbookComponent(
                  name: 'Semantic Tokens',
                  useCases: [
                    WidgetbookUseCase(
                      name: 'All Tokens',
                      builder: (context) => const _SemanticColorsPreview(),
                    ),
                  ],
                ),
              ],
            ),

            // Typography
            WidgetbookFolder(
              name: 'Typography',
              children: [
                WidgetbookComponent(
                  name: 'Type Scale',
                  useCases: [
                    WidgetbookUseCase(
                      name: 'Display Styles',
                      builder: (context) => const _TypographyPreview(
                        category: 'Display',
                      ),
                    ),
                    WidgetbookUseCase(
                      name: 'Headline Styles',
                      builder: (context) => const _TypographyPreview(
                        category: 'Headline',
                      ),
                    ),
                    WidgetbookUseCase(
                      name: 'Title Styles',
                      builder: (context) => const _TypographyPreview(
                        category: 'Title',
                      ),
                    ),
                    WidgetbookUseCase(
                      name: 'Label Styles',
                      builder: (context) => const _TypographyPreview(
                        category: 'Label',
                      ),
                    ),
                    WidgetbookUseCase(
                      name: 'Body Styles',
                      builder: (context) => const _TypographyPreview(
                        category: 'Body',
                      ),
                    ),
                    WidgetbookUseCase(
                      name: 'All Styles',
                      builder: (context) => const _TypographyPreview(
                        category: 'All',
                      ),
                    ),
                  ],
                ),
              ],
            ),

            // Spacing
            WidgetbookFolder(
              name: 'Spacing',
              children: [
                WidgetbookComponent(
                  name: 'Spacing Scale',
                  useCases: [
                    WidgetbookUseCase(
                      name: 'All Tokens',
                      builder: (context) => const _SpacingPreview(),
                    ),
                  ],
                ),
              ],
            ),

            // Radius
            WidgetbookFolder(
              name: 'Radius',
              children: [
                WidgetbookComponent(
                  name: 'Border Radius',
                  useCases: [
                    WidgetbookUseCase(
                      name: 'All Tokens',
                      builder: (context) => const _RadiusPreview(),
                    ),
                  ],
                ),
              ],
            ),

            // Elevation
            WidgetbookFolder(
              name: 'Elevation',
              children: [
                WidgetbookComponent(
                  name: 'Shadow Levels',
                  useCases: [
                    WidgetbookUseCase(
                      name: 'All Levels',
                      builder: (context) => const _ElevationPreview(),
                    ),
                  ],
                ),
              ],
            ),
          ],
        ),

        // =====================================================================
        // COMPONENTS (Placeholder for future components)
        // =====================================================================
        WidgetbookCategory(
          name: 'Components',
          children: [
            WidgetbookFolder(
              name: 'Buttons',
              children: [
                WidgetbookComponent(
                  name: 'Elevated Button',
                  useCases: [
                    WidgetbookUseCase(
                      name: 'Default',
                      builder: (context) => const _ButtonPreview(),
                    ),
                  ],
                ),
              ],
            ),
            WidgetbookFolder(
              name: 'Inputs',
              children: [
                WidgetbookComponent(
                  name: 'Text Field',
                  useCases: [
                    WidgetbookUseCase(
                      name: 'Default',
                      builder: (context) => const _TextFieldPreview(),
                    ),
                  ],
                ),
              ],
            ),
            WidgetbookFolder(
              name: 'Cards',
              children: [
                WidgetbookComponent(
                  name: 'Card',
                  useCases: [
                    WidgetbookUseCase(
                      name: 'Default',
                      builder: (context) => const _CardPreview(),
                    ),
                  ],
                ),
              ],
            ),
          ],
        ),
      ],
    );
  }
}

// =============================================================================
// BRAND ADDON WRAPPER
// =============================================================================

class _BrandAddonWrapper extends StatefulWidget {
  const _BrandAddonWrapper({required this.child});

  final Widget child;

  @override
  State<_BrandAddonWrapper> createState() => _BrandAddonWrapperState();
}

class _BrandAddonWrapperState extends State<_BrandAddonWrapper> {
  SingularBrand _selectedBrand = SingularBrand.walaPlus;

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        // Brand selector
        Container(
          padding: const EdgeInsets.all(8),
          color: Colors.grey.shade200,
          child: Row(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              const Text('Brand: ', style: TextStyle(fontWeight: FontWeight.bold)),
              const SizedBox(width: 8),
              SegmentedButton<SingularBrand>(
                segments: SingularBrand.values.map((brand) {
                  return ButtonSegment<SingularBrand>(
                    value: brand,
                    label: Text(brand.displayName),
                  );
                }).toList(),
                selected: {_selectedBrand},
                onSelectionChanged: (selection) {
                  setState(() {
                    _selectedBrand = selection.first;
                  });
                },
              ),
            ],
          ),
        ),
        // Content with brand context
        Expanded(
          child: _BrandContext(
            brand: _selectedBrand,
            child: widget.child,
          ),
        ),
      ],
    );
  }
}

class _BrandContext extends InheritedWidget {
  const _BrandContext({
    required this.brand,
    required super.child,
  });

  final SingularBrand brand;

  static SingularBrand of(BuildContext context) {
    final widget = context.dependOnInheritedWidgetOfExactType<_BrandContext>();
    return widget?.brand ?? SingularBrand.walaPlus;
  }

  @override
  bool updateShouldNotify(_BrandContext oldWidget) => brand != oldWidget.brand;
}

// =============================================================================
// PREVIEW WIDGETS
// =============================================================================

/// Color swatch preview widget
class _ColorSwatchPreview extends StatelessWidget {
  const _ColorSwatchPreview({
    required this.name,
    required this.swatch,
  });

  final String name;
  final Map<int, Color> swatch;

  @override
  Widget build(BuildContext context) {
    final colors = context.colors;
    final typography = context.typography;

    return Scaffold(
      backgroundColor: colors.bgPrimary,
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(
              name,
              style: typography.headlineMedium.copyWith(color: colors.textPrimary),
            ),
            const SizedBox(height: 16),
            ...swatch.entries.map((entry) {
              final step = entry.key;
              final color = entry.value;
              final hexCode = '#${color.value.toRadixString(16).substring(2).toUpperCase()}';
              final isLight = color.computeLuminance() > 0.5;

              return Container(
                height: 60,
                margin: const EdgeInsets.only(bottom: 4),
                decoration: BoxDecoration(
                  color: color,
                  borderRadius: BorderRadius.circular(8),
                ),
                padding: const EdgeInsets.symmetric(horizontal: 16),
                child: Row(
                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  children: [
                    Text(
                      step.toString(),
                      style: TextStyle(
                        color: isLight ? Colors.black : Colors.white,
                        fontWeight: FontWeight.bold,
                        fontSize: 16,
                      ),
                    ),
                    Text(
                      hexCode,
                      style: TextStyle(
                        color: isLight ? Colors.black54 : Colors.white70,
                        fontSize: 14,
                        fontFamily: 'monospace',
                      ),
                    ),
                  ],
                ),
              );
            }),
          ],
        ),
      ),
    );
  }
}

/// Semantic colors preview widget
class _SemanticColorsPreview extends StatelessWidget {
  const _SemanticColorsPreview();

  @override
  Widget build(BuildContext context) {
    final colors = context.colors;
    final typography = context.typography;

    return Scaffold(
      backgroundColor: colors.bgPrimary,
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            _ColorSection(
              title: 'Backgrounds',
              colors: {
                'bgPrimary': colors.bgPrimary,
                'bgSecondary': colors.bgSecondary,
                'bgSurface': colors.bgSurface,
                'bgSurfaceSoft': colors.bgSurfaceSoft,
                'bgSurfaceInverse': colors.bgSurfaceInverse,
              },
              typography: typography,
              textColor: colors.textPrimary,
            ),
            const SizedBox(height: 24),
            _ColorSection(
              title: 'Text',
              colors: {
                'textPrimary': colors.textPrimary,
                'textSecondary': colors.textSecondary,
                'textDisabled': colors.textDisabled,
                'textInverse': colors.textInverse,
                'textOnColor': colors.textOnColor,
              },
              typography: typography,
              textColor: colors.textPrimary,
            ),
            const SizedBox(height: 24),
            _ColorSection(
              title: 'Borders',
              colors: {
                'borderWeak': colors.borderWeak,
                'borderDefault': colors.borderDefault,
                'borderStrong': colors.borderStrong,
                'borderFocus': colors.borderFocus,
              },
              typography: typography,
              textColor: colors.textPrimary,
            ),
            const SizedBox(height: 24),
            _ColorSection(
              title: 'Status',
              colors: {
                'statusSuccess': colors.statusSuccess,
                'statusWarning': colors.statusWarning,
                'statusError': colors.statusError,
                'statusInfo': colors.statusInfo,
              },
              typography: typography,
              textColor: colors.textPrimary,
            ),
            const SizedBox(height: 24),
            _ColorSection(
              title: 'Brand',
              colors: {
                'brandPrimary': colors.brandPrimary,
                'brandSecondary': colors.brandSecondary,
                'brandPrimaryLight': colors.brandPrimaryLight,
                'brandPrimaryDark': colors.brandPrimaryDark,
              },
              typography: typography,
              textColor: colors.textPrimary,
            ),
          ],
        ),
      ),
    );
  }
}

class _ColorSection extends StatelessWidget {
  const _ColorSection({
    required this.title,
    required this.colors,
    required this.typography,
    required this.textColor,
  });

  final String title;
  final Map<String, Color> colors;
  final AppTypography typography;
  final Color textColor;

  @override
  Widget build(BuildContext context) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          title,
          style: typography.titleLarge.copyWith(color: textColor),
        ),
        const SizedBox(height: 12),
        Wrap(
          spacing: 12,
          runSpacing: 12,
          children: colors.entries.map((entry) {
            final isLight = entry.value.computeLuminance() > 0.5;
            return Container(
              width: 120,
              height: 80,
              decoration: BoxDecoration(
                color: entry.value,
                borderRadius: BorderRadius.circular(8),
                border: Border.all(
                  color: isLight ? Colors.black12 : Colors.white12,
                ),
              ),
              padding: const EdgeInsets.all(8),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                mainAxisAlignment: MainAxisAlignment.end,
                children: [
                  Text(
                    entry.key,
                    style: TextStyle(
                      color: isLight ? Colors.black : Colors.white,
                      fontSize: 10,
                      fontWeight: FontWeight.w500,
                    ),
                  ),
                ],
              ),
            );
          }).toList(),
        ),
      ],
    );
  }
}

/// Typography preview widget
class _TypographyPreview extends StatelessWidget {
  const _TypographyPreview({required this.category});

  final String category;

  @override
  Widget build(BuildContext context) {
    final colors = context.colors;
    final typography = context.typography;

    final Map<String, TextStyle> styles = {};

    if (category == 'Display' || category == 'All') {
      styles.addAll({
        'displayLarge (57px)': typography.displayLarge,
        'displayMedium (45px)': typography.displayMedium,
        'displaySmall (36px)': typography.displaySmall,
      });
    }

    if (category == 'Headline' || category == 'All') {
      styles.addAll({
        'headlineLarge (32px)': typography.headlineLarge,
        'headlineMedium (28px)': typography.headlineMedium,
        'headlineSmall (24px)': typography.headlineSmall,
      });
    }

    if (category == 'Title' || category == 'All') {
      styles.addAll({
        'titleLarge (22px)': typography.titleLarge,
        'titleMedium (16px)': typography.titleMedium,
        'titleSmall (14px)': typography.titleSmall,
      });
    }

    if (category == 'Label' || category == 'All') {
      styles.addAll({
        'labelLarge (14px)': typography.labelLarge,
        'labelMedium (12px)': typography.labelMedium,
        'labelSmall (11px)': typography.labelSmall,
      });
    }

    if (category == 'Body' || category == 'All') {
      styles.addAll({
        'bodyLarge (16px)': typography.bodyLarge,
        'bodyMedium (14px)': typography.bodyMedium,
        'bodySmall (12px)': typography.bodySmall,
      });
    }

    return Scaffold(
      backgroundColor: colors.bgPrimary,
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(
              '$category Styles',
              style: typography.headlineMedium.copyWith(color: colors.textPrimary),
            ),
            const SizedBox(height: 8),
            Text(
              'Font Family: ${typography.fontFamily}',
              style: typography.bodySmall.copyWith(color: colors.textSecondary),
            ),
            const SizedBox(height: 24),
            ...styles.entries.map((entry) {
              return Padding(
                padding: const EdgeInsets.only(bottom: 16),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      entry.key,
                      style: typography.labelSmall.copyWith(
                        color: colors.textSecondary,
                      ),
                    ),
                    const SizedBox(height: 4),
                    Text(
                      'The quick brown fox jumps over the lazy dog',
                      style: entry.value.copyWith(color: colors.textPrimary),
                    ),
                    const Divider(),
                  ],
                ),
              );
            }),
          ],
        ),
      ),
    );
  }
}

/// Spacing preview widget
class _SpacingPreview extends StatelessWidget {
  const _SpacingPreview();

  @override
  Widget build(BuildContext context) {
    final colors = context.colors;
    final typography = context.typography;
    final spacing = context.spacing;

    final spacingTokens = {
      'none': spacing.none,
      'xxs (2px)': spacing.xxs,
      'xs (4px)': spacing.xs,
      'sm (8px)': spacing.sm,
      'md (12px)': spacing.md,
      'lg (16px)': spacing.lg,
      'xl (20px)': spacing.xl,
      'xxl (24px)': spacing.xxl,
      'section (32px)': spacing.section,
      'sectionLg (48px)': spacing.sectionLg,
      'sectionXl (64px)': spacing.sectionXl,
    };

    return Scaffold(
      backgroundColor: colors.bgPrimary,
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(
              'Spacing Scale',
              style: typography.headlineMedium.copyWith(color: colors.textPrimary),
            ),
            const SizedBox(height: 8),
            Text(
              'Base unit: ${spacing.baseUnit}px',
              style: typography.bodySmall.copyWith(color: colors.textSecondary),
            ),
            const SizedBox(height: 24),
            ...spacingTokens.entries.map((entry) {
              return Padding(
                padding: const EdgeInsets.only(bottom: 12),
                child: Row(
                  children: [
                    SizedBox(
                      width: 120,
                      child: Text(
                        entry.key,
                        style: typography.labelMedium.copyWith(
                          color: colors.textSecondary,
                        ),
                      ),
                    ),
                    Container(
                      width: entry.value,
                      height: 24,
                      decoration: BoxDecoration(
                        color: colors.brandPrimary,
                        borderRadius: BorderRadius.circular(4),
                      ),
                    ),
                    const SizedBox(width: 8),
                    Text(
                      '${entry.value.toInt()}px',
                      style: typography.bodySmall.copyWith(
                        color: colors.textDisabled,
                      ),
                    ),
                  ],
                ),
              );
            }),
          ],
        ),
      ),
    );
  }
}

/// Radius preview widget
class _RadiusPreview extends StatelessWidget {
  const _RadiusPreview();

  @override
  Widget build(BuildContext context) {
    final colors = context.colors;
    final typography = context.typography;
    final radius = context.radius;

    final radiusTokens = {
      'none (0px)': radius.none,
      'xs (4px)': radius.xs,
      'sm (8px)': radius.sm,
      'md (12px)': radius.md,
      'lg (16px)': radius.lg,
      'xl (24px)': radius.xl,
      'full (999px)': radius.full,
    };

    return Scaffold(
      backgroundColor: colors.bgPrimary,
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(
              'Border Radius',
              style: typography.headlineMedium.copyWith(color: colors.textPrimary),
            ),
            const SizedBox(height: 24),
            Wrap(
              spacing: 16,
              runSpacing: 16,
              children: radiusTokens.entries.map((entry) {
                return Column(
                  children: [
                    Container(
                      width: 80,
                      height: 80,
                      decoration: BoxDecoration(
                        color: colors.brandPrimary,
                        borderRadius: entry.value,
                      ),
                    ),
                    const SizedBox(height: 8),
                    Text(
                      entry.key,
                      style: typography.labelSmall.copyWith(
                        color: colors.textSecondary,
                      ),
                    ),
                  ],
                );
              }).toList(),
            ),
          ],
        ),
      ),
    );
  }
}

/// Elevation preview widget
class _ElevationPreview extends StatelessWidget {
  const _ElevationPreview();

  @override
  Widget build(BuildContext context) {
    final colors = context.colors;
    final typography = context.typography;
    final elevation = context.elevation;
    final radius = context.radius;

    final elevationLevels = {
      'level0 (None)': elevation.level0,
      'level1 (Subtle)': elevation.level1,
      'level2 (Medium)': elevation.level2,
      'level3 (High)': elevation.level3,
      'level4 (Highest)': elevation.level4,
    };

    return Scaffold(
      backgroundColor: colors.bgSecondary,
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(24),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(
              'Elevation Levels',
              style: typography.headlineMedium.copyWith(color: colors.textPrimary),
            ),
            const SizedBox(height: 24),
            ...elevationLevels.entries.map((entry) {
              return Padding(
                padding: const EdgeInsets.only(bottom: 24),
                child: Row(
                  children: [
                    Container(
                      width: 120,
                      height: 80,
                      decoration: BoxDecoration(
                        color: colors.bgSurface,
                        borderRadius: radius.md,
                        boxShadow: entry.value,
                      ),
                      alignment: Alignment.center,
                      child: Text(
                        entry.key.split(' ')[0],
                        style: typography.labelMedium.copyWith(
                          color: colors.textSecondary,
                        ),
                      ),
                    ),
                    const SizedBox(width: 16),
                    Text(
                      entry.key,
                      style: typography.bodyMedium.copyWith(
                        color: colors.textPrimary,
                      ),
                    ),
                  ],
                ),
              );
            }),
          ],
        ),
      ),
    );
  }
}

/// Button preview widget
class _ButtonPreview extends StatelessWidget {
  const _ButtonPreview();

  @override
  Widget build(BuildContext context) {
    final colors = context.colors;
    final typography = context.typography;

    return Scaffold(
      backgroundColor: colors.bgPrimary,
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(24),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(
              'Buttons',
              style: typography.headlineMedium.copyWith(color: colors.textPrimary),
            ),
            const SizedBox(height: 24),
            // Elevated Button
            Text(
              'Elevated Button',
              style: typography.titleMedium.copyWith(color: colors.textSecondary),
            ),
            const SizedBox(height: 8),
            ElevatedButton(
              onPressed: () {},
              child: const Text('Primary Action'),
            ),
            const SizedBox(height: 8),
            ElevatedButton(
              onPressed: null,
              child: const Text('Disabled'),
            ),
            const SizedBox(height: 24),
            // Outlined Button
            Text(
              'Outlined Button',
              style: typography.titleMedium.copyWith(color: colors.textSecondary),
            ),
            const SizedBox(height: 8),
            OutlinedButton(
              onPressed: () {},
              child: const Text('Secondary Action'),
            ),
            const SizedBox(height: 24),
            // Text Button
            Text(
              'Text Button',
              style: typography.titleMedium.copyWith(color: colors.textSecondary),
            ),
            const SizedBox(height: 8),
            TextButton(
              onPressed: () {},
              child: const Text('Tertiary Action'),
            ),
          ],
        ),
      ),
    );
  }
}

/// Text field preview widget
class _TextFieldPreview extends StatelessWidget {
  const _TextFieldPreview();

  @override
  Widget build(BuildContext context) {
    final colors = context.colors;
    final typography = context.typography;

    return Scaffold(
      backgroundColor: colors.bgPrimary,
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(24),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(
              'Text Fields',
              style: typography.headlineMedium.copyWith(color: colors.textPrimary),
            ),
            const SizedBox(height: 24),
            const TextField(
              decoration: InputDecoration(
                labelText: 'Label',
                hintText: 'Enter text...',
              ),
            ),
            const SizedBox(height: 16),
            const TextField(
              decoration: InputDecoration(
                labelText: 'With Helper',
                hintText: 'Enter text...',
                helperText: 'This is helper text',
              ),
            ),
            const SizedBox(height: 16),
            const TextField(
              decoration: InputDecoration(
                labelText: 'With Error',
                hintText: 'Enter text...',
                errorText: 'This field is required',
              ),
            ),
            const SizedBox(height: 16),
            const TextField(
              enabled: false,
              decoration: InputDecoration(
                labelText: 'Disabled',
                hintText: 'Cannot edit...',
              ),
            ),
          ],
        ),
      ),
    );
  }
}

/// Card preview widget
class _CardPreview extends StatelessWidget {
  const _CardPreview();

  @override
  Widget build(BuildContext context) {
    final colors = context.colors;
    final typography = context.typography;
    final spacing = context.spacing;
    final elevation = context.elevation;

    return Scaffold(
      backgroundColor: colors.bgSecondary,
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(24),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(
              'Cards',
              style: typography.headlineMedium.copyWith(color: colors.textPrimary),
            ),
            const SizedBox(height: 24),
            Card(
              child: Padding(
                padding: spacing.cardInsets,
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      'Card Title',
                      style: typography.titleMedium.copyWith(
                        color: colors.textPrimary,
                      ),
                    ),
                    const SizedBox(height: 8),
                    Text(
                      'This is a card component using the design system tokens.',
                      style: typography.bodyMedium.copyWith(
                        color: colors.textSecondary,
                      ),
                    ),
                  ],
                ),
              ),
            ),
            const SizedBox(height: 16),
            Container(
              decoration: BoxDecoration(
                color: colors.bgSurface,
                borderRadius: BorderRadius.circular(12),
                boxShadow: elevation.level2,
              ),
              padding: spacing.cardInsets,
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    'Elevated Card',
                    style: typography.titleMedium.copyWith(
                      color: colors.textPrimary,
                    ),
                  ),
                  const SizedBox(height: 8),
                  Text(
                    'This card uses elevation level 2 for a subtle shadow.',
                    style: typography.bodyMedium.copyWith(
                      color: colors.textSecondary,
                    ),
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }
}

